### ISSUE TITLE
How do you deal with circular references?

### ISSUE THREAD

**Issue by marcobambini** [Electrux/Ethereal#8]
In you article https://medium.com/young-coder/so-i-created-a-programming-language-4d9c11038d22 you mentioned that you use reference counting, but how do you deal with circular references? Is there any trick to prevent it?

**Comment by Chirag-Khandelwal** [comment]
The trick is simply that circular references don't ever occur. Any simple initialization variable always copies the RHS object. Even in optionals (modules/std/opt.cpp), when you set it, the variable is actually copied by it instead of having its reference count increased. This is done to prevent having circular references and having segfaults on using the structure with such data.
